import 'package:khaanado/constants/asset_constants.dart';
import 'package:khaanado/model/food_item.dart';

class CatalogSeed {
  CatalogSeed._();

  static const categories = <FoodCategory>[
    FoodCategory(id: 'burger', name: 'Burgers', image: AssetConstants.burger),
    FoodCategory(id: 'pizza', name: 'Pizza', image: AssetConstants.pizza),
    FoodCategory(id: 'meals', name: 'Meals', image: AssetConstants.biryani),
    FoodCategory(id: 'south', name: 'South', image: AssetConstants.dosa),
    FoodCategory(id: 'drinks', name: 'Drinks', image: AssetConstants.soda),
    FoodCategory(id: 'dessert', name: 'Dessert', image: AssetConstants.dessert),
  ];

  static const items = <FoodItem>[
    FoodItem(
      id: 'classic_burger',
      name: 'Classic Burger',
      image: AssetConstants.burger,
      price: 149,
      rating: 4.5,
      prepMinutes: 20,
      categoryId: 'burger',
      description:
          'Grilled patty, cheddar, lettuce and house sauce on a toasted bun.',
      isVeg: false,
      isPopular: true,
      reviewCount: 312,
      kitchen: 'Grill House',
    ),
    FoodItem(
      id: 'smoky_burger',
      name: 'Smoky Burger',
      image: AssetConstants.burger2,
      price: 179,
      rating: 4.6,
      prepMinutes: 22,
      categoryId: 'burger',
      description:
          'Char-grilled patty with smoked paprika mayo and caramelised onion.',
      isVeg: false,
      isPopular: true,
      reviewCount: 198,
      kitchen: 'Grill House',
    ),
    FoodItem(
      id: 'margherita',
      name: 'Margherita Pizza',
      image: AssetConstants.pizza,
      price: 229,
      rating: 4.4,
      prepMinutes: 25,
      categoryId: 'pizza',
      description: 'San Marzano tomato, mozzarella and fresh basil on wood-fired crust.',
      isVeg: true,
      isPopular: true,
      reviewCount: 540,
      kitchen: 'Woodfire Co.',
    ),
    FoodItem(
      id: 'farmhouse',
      name: 'Farmhouse Pizza',
      image: AssetConstants.pizza2,
      price: 279,
      rating: 4.7,
      prepMinutes: 28,
      categoryId: 'pizza',
      description:
          'Capsicum, onion, mushroom and olives on a cheese-loaded base.',
      isVeg: true,
      isPopular: true,
      reviewCount: 421,
      kitchen: 'Woodfire Co.',
    ),
    FoodItem(
      id: 'alfredo',
      name: 'Alfredo Pasta',
      image: AssetConstants.pasta,
      price: 199,
      rating: 4.3,
      prepMinutes: 18,
      categoryId: 'meals',
      description: 'Fettuccine in creamy alfredo sauce finished with parmesan.',
      isVeg: true,
      isPopular: true,
      reviewCount: 166,
      kitchen: 'Pasta Lane',
    ),
    FoodItem(
      id: 'biryani',
      name: 'Hyderabadi Biryani',
      image: AssetConstants.biryani,
      price: 249,
      rating: 4.8,
      prepMinutes: 30,
      categoryId: 'meals',
      description:
          'Slow-cooked basmati, warm spices and raita. A KhaanaDo signature.',
      isVeg: false,
      isPopular: true,
      reviewCount: 890,
      kitchen: 'Dum Kitchen',
    ),
    FoodItem(
      id: 'paneer_rice',
      name: 'Paneer Rice Bowl',
      image: AssetConstants.rice,
      price: 179,
      rating: 4.2,
      prepMinutes: 16,
      categoryId: 'meals',
      description: 'Jeera rice topped with butter paneer and pickled onion.',
      isVeg: true,
      isPopular: false,
      reviewCount: 94,
      kitchen: 'Pasta Lane',
    ),
    FoodItem(
      id: 'masala_dosa',
      name: 'Masala Dosa',
      image: AssetConstants.dosa,
      price: 129,
      rating: 4.6,
      prepMinutes: 15,
      categoryId: 'south',
      description: 'Crisp dosa, spiced potato filling, coconut chutney and sambar.',
      isVeg: true,
      isPopular: true,
      reviewCount: 275,
      kitchen: 'South Fold',
    ),
    FoodItem(
      id: 'lemon_soda',
      name: 'Lemon Soda',
      image: AssetConstants.soda,
      price: 49,
      rating: 4.1,
      prepMinutes: 5,
      categoryId: 'drinks',
      description: 'Chilled soda with fresh lemon, black salt and mint.',
      isVeg: true,
      isPopular: false,
      reviewCount: 61,
      kitchen: 'The Pour',
    ),
    FoodItem(
      id: 'cold_coffee',
      name: 'Cold Coffee',
      image: AssetConstants.coffee,
      price: 89,
      rating: 4.4,
      prepMinutes: 8,
      categoryId: 'drinks',
      description: 'Blended espresso, milk and a light chocolate finish.',
      isVeg: true,
      isPopular: false,
      reviewCount: 143,
      kitchen: 'The Pour',
    ),
    FoodItem(
      id: 'mojito',
      name: 'Fresh Mojito',
      image: AssetConstants.mojito,
      price: 99,
      rating: 4.5,
      prepMinutes: 7,
      categoryId: 'drinks',
      description: 'Mudled mint, lime and soda. Zero proof, full refresh.',
      isVeg: true,
      isPopular: true,
      reviewCount: 210,
      kitchen: 'The Pour',
    ),
    FoodItem(
      id: 'lava_cake',
      name: 'Lava Cake',
      image: AssetConstants.dessert,
      price: 159,
      rating: 4.7,
      prepMinutes: 12,
      categoryId: 'dessert',
      description: 'Warm chocolate cake with a molten centre and vanilla scoop.',
      isVeg: true,
      isPopular: true,
      reviewCount: 388,
      kitchen: 'Sweet Counter',
    ),
    FoodItem(
      id: 'veggie_burger',
      name: 'Crispy Veggie Burger',
      image: AssetConstants.burger,
      price: 139,
      rating: 4.4,
      prepMinutes: 18,
      categoryId: 'burger',
      description:
          'Crisp potato-pea patty, lettuce, tomato and mint mayo on a toasted bun.',
      isVeg: true,
      isPopular: true,
      reviewCount: 247,
      kitchen: 'Grill House',
    ),
    FoodItem(
      id: 'tikka_burger',
      name: 'Chicken Tikka Burger',
      image: AssetConstants.burger2,
      price: 189,
      rating: 4.6,
      prepMinutes: 22,
      categoryId: 'burger',
      description:
          'Tandoori chicken, pickled onion and mint yoghurt in a brioche bun.',
      isVeg: false,
      isPopular: true,
      reviewCount: 331,
      kitchen: 'Grill House',
    ),
    FoodItem(
      id: 'pepperoni',
      name: 'Pepperoni Pizza',
      image: AssetConstants.pizza2,
      price: 299,
      rating: 4.6,
      prepMinutes: 26,
      categoryId: 'pizza',
      description: 'Spicy pepperoni, mozzarella and chilli oil on a wood-fired base.',
      isVeg: false,
      isPopular: true,
      reviewCount: 412,
      kitchen: 'Woodfire Co.',
    ),
    FoodItem(
      id: 'paneer_pizza',
      name: 'Paneer Tikka Pizza',
      image: AssetConstants.pizza,
      price: 269,
      rating: 4.5,
      prepMinutes: 25,
      categoryId: 'pizza',
      description: 'Tandoori paneer, capsicum and onion on a spicy tomato base.',
      isVeg: true,
      isPopular: true,
      reviewCount: 288,
      kitchen: 'Woodfire Co.',
    ),
    FoodItem(
      id: 'butter_chicken',
      name: 'Butter Chicken',
      image: AssetConstants.biryani,
      price: 269,
      rating: 4.8,
      prepMinutes: 28,
      categoryId: 'meals',
      description: 'Creamy tomato gravy, tender chicken, butter naan on the side.',
      isVeg: false,
      isPopular: true,
      reviewCount: 764,
      kitchen: 'Dum Kitchen',
    ),
    FoodItem(
      id: 'veg_thali',
      name: 'Veg Thali',
      image: AssetConstants.rice,
      price: 189,
      rating: 4.5,
      prepMinutes: 20,
      categoryId: 'meals',
      description: 'Dal, sabzi, rice, roti, pickle and a sweet. Full plate, no fuss.',
      isVeg: true,
      isPopular: true,
      reviewCount: 219,
      kitchen: 'Pasta Lane',
    ),
    FoodItem(
      id: 'chicken_fried_rice',
      name: 'Chicken Fried Rice',
      image: AssetConstants.rice,
      price: 169,
      rating: 4.3,
      prepMinutes: 16,
      categoryId: 'meals',
      description: 'Wok-tossed rice, egg, chicken and spring onion.',
      isVeg: false,
      isPopular: false,
      reviewCount: 156,
      kitchen: 'Dum Kitchen',
    ),
    FoodItem(
      id: 'idli_sambar',
      name: 'Idli Sambar',
      image: AssetConstants.dosa,
      price: 99,
      rating: 4.6,
      prepMinutes: 12,
      categoryId: 'south',
      description: 'Soft idlis, hot sambar and coconut chutney.',
      isVeg: true,
      isPopular: true,
      reviewCount: 402,
      kitchen: 'South Fold',
    ),
    FoodItem(
      id: 'medu_vada',
      name: 'Medu Vada',
      image: AssetConstants.dosa,
      price: 89,
      rating: 4.4,
      prepMinutes: 14,
      categoryId: 'south',
      description: 'Crisp urad vadas soaked just enough, with extra sambar.',
      isVeg: true,
      isPopular: false,
      reviewCount: 173,
      kitchen: 'South Fold',
    ),
    FoodItem(
      id: 'filter_coffee',
      name: 'Filter Coffee',
      image: AssetConstants.coffee,
      price: 59,
      rating: 4.5,
      prepMinutes: 6,
      categoryId: 'drinks',
      description: 'South Indian decoction, whole milk, served strong.',
      isVeg: true,
      isPopular: true,
      reviewCount: 228,
      kitchen: 'The Pour',
    ),
    FoodItem(
      id: 'mango_lassi',
      name: 'Mango Lassi',
      image: AssetConstants.mojito,
      price: 79,
      rating: 4.6,
      prepMinutes: 5,
      categoryId: 'drinks',
      description: 'Alphonso mango, yoghurt and a pinch of cardamom.',
      isVeg: true,
      isPopular: true,
      reviewCount: 301,
      kitchen: 'The Pour',
    ),
    FoodItem(
      id: 'masala_chaas',
      name: 'Masala Chaas',
      image: AssetConstants.soda,
      price: 49,
      rating: 4.2,
      prepMinutes: 4,
      categoryId: 'drinks',
      description: 'Buttermilk with roasted cumin, curry leaf and chilli.',
      isVeg: true,
      isPopular: false,
      reviewCount: 88,
      kitchen: 'The Pour',
    ),
    FoodItem(
      id: 'gulab_jamun',
      name: 'Gulab Jamun',
      image: AssetConstants.dessert,
      price: 99,
      rating: 4.6,
      prepMinutes: 8,
      categoryId: 'dessert',
      description: 'Warm khoya dumplings in rose syrup. Two pieces.',
      isVeg: true,
      isPopular: true,
      reviewCount: 455,
      kitchen: 'Sweet Counter',
    ),
    FoodItem(
      id: 'brownie',
      name: 'Walnut Brownie',
      image: AssetConstants.dessert,
      price: 129,
      rating: 4.5,
      prepMinutes: 10,
      categoryId: 'dessert',
      description: 'Fudgy brownie, toasted walnut, served slightly warm.',
      isVeg: true,
      isPopular: false,
      reviewCount: 190,
      kitchen: 'Sweet Counter',
    ),
  ];
}
